# Generated by Django 4.1.3 on 2023-04-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profil_img',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='profil-fotoğrafı'),
        ),
    ]
