# Generated by Django 4.1.3 on 2023-04-09 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0007_profil_date_created_alter_profil_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profil',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
