# Generated by Django 4.1.3 on 2023-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_remove_profil_birth_date_profil_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profil_img',
            field=models.ImageField(blank=True, default='img/default-profile-img.png', null=True, upload_to='image', verbose_name='profil-fotoğrafı'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
